### PR TITLE
chore(deps-dev): bump react-router-dom from 5.3.0 to 6.0.0

### PR DESCRIPTION
**Pull request by Valtas**
Bumps [react-router-dom](https://github.com/remix-run/react-router/tree/HEAD/packages/react-router-dom) from 5.3.0 to 6.0.0.
- [Release notes](https://github.com/remix-run/react-router/releases)
- [Commits](https://github.com/remix-run/react-router/commits/v6.0.0/packages/react-router-dom)

---
updated-dependencies:
- dependency-name: react-router-dom
  dependency-type: direct:development
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by iSverdlov — COMMENTED** [review]
Что это?

**Review by iSverdlov — DISMISSED** [review]

**Review by iSverdlov — COMMENTED** [review]
ывапыв

**Comment by Valtas** [comment]
sdf

**Comment by Valtas** [comment]
sdf

**Review by iSverdlov — APPROVED** [review]

**Comment by Valtas** [comment]
sdf

**Comment by Valtas** [comment]
sdf

**Comment by Valtas** [comment]
sdfsdfsdf

**Comment by Valtas** [comment]
sdfsdf

**Pull request merged**
